name: build
on: [push]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    environment: artifactory
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build -Partifactory_contextUrl=${{ secrets.ARTIFACTORY_CONTEXT_URL }} -Partifactory_user=${{ secrets.ARTIFACTORY_USER }} -Partifactory_password=${{ secrets.ARTIFACTORY_PASSWORD }}